" .vimrc
"filetype plugin indent on
syntax on

" Uncomment the following to have Vim jump to the last position when
" reopening a file
if has("autocmd")
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
endif

set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set ts=4
set expandtab
"set number
set modelines=5
set ruler
